### PR TITLE
Re-orginze the plugin as instantiated classes

### PR DESCRIPTION
**Pull request by nash-ye**
As discussed in the issue #31 , We want to re-organize the plugin to have more professional OOP style.

@westonruter said:

> In general, I believe the smaller the class the better. The more that classes (and methods) do just one thing and 
> do it well, the easier it will be to maintain the plugin and (especially) be able to write unit tests, as each 
> component class of the plugin can be replaced with another component that implements the same interface. You 
> know, mocks and dependency injection.

You can read the full-discussion in  the issue #31

 so.. as starting point we want to agree on the scheme pattern and the needed classes.

What is the classes names prefix shall we use? `DepMin_` or `Dependency_Minification_` ?
How many classes can you separate the plugin to, and what they are? (write a names)
...etc

### CODE REVIEW

**Comment by westonruter** [comment]
Just off the top of my head, I think a class for Options and a class for Admin page would make sense (depends on #27). It would also be great if each minifier were implemented as a [strategy](http://en.wikipedia.org/wiki/Strategy_pattern), so that they could be easily swapped out (this relates to #7). So off the top of my head, we could have:
- `Dependency_Minification`
- `Dependency_Minification_Options` (extends `ArrayObject`)
- `Dependency_Minification_Minifier` (abstract class, extended by each strategy)
- `Dependency_Minification_Admin_Page` (handles Settings API, adding admin page, etc)

**Comment by nash-ye** [comment]
@westonruter Nice suggestions, and make full-sense for a starting point... I will start coding today.

**Comment by nash-ye** [comment]
@westonruter Which you prefer for the classes names prefix? `DepMin` or `Dependency_Minification` ?
I think the shorter one is better.

**Comment by westonruter** [comment]
@nash-ye humm, I guess for the main plugin class it should remain `Dependency_Minfication`, but then the other classes in the plugin can freely use the shorter `DepMin` prefix. I can't wait until we can use PHP namespaces without worrying about compatibility!

**Comment by westonruter** [comment]
Pull requests #27 and #37 should get merged before the major refactor work.

**Comment by nash-ye** [comment]
Finally I had finished my exams today, I will complete this PR very soon, 
Thank you for your patience, I really appreciate it :)

Eid Mubarak!

**Comment by westonruter** [comment]
@nash-ye :+1: Happy Eid!

I still need to finish reviewing @shadyvb's work on #27 before a refactor should happen. I did leave some feedback for him.

**Comment by nash-ye** [comment]
Thanks @westonruter It was a nice happy day :)
I give some notes to @shadyvb too.. I can't wait to finish this PR :100:

**Comment by shadyvb** [comment]
All set, i took care of all comments.

**Comment by nash-ye** [comment]
@shadyvb This has been open too long, Please tell me when you finish your PR.

**Comment by westonruter** [comment]
The PR has been merged into develop. Now we're just looking at applying
PHP_CodeSniffer fixes.

**Comment by nash-ye** [comment]
Thanks @westonruter , So can we do this PR in 1.0 realase?

**Comment by westonruter** [comment]
Yes, sounds good.

**Comment by nash-ye** [comment]
This pull on prograss. The classes that I have done for now are
`DepMin_Options`
`DepMin_Cache`
`DepMin_Cache_Interface`
`DepMin_Cache_In_WP_Options`
`DepMin_Settings_Page`

The first commit will be ready in the next two days... stay tuned!

**Comment by westonruter** [comment]
@nash-ye what is `DepMin_Cache_In_WP_Options` for?

**Comment by nash-ye** [comment]
@westonruter I have split the cache process to some small classes (slimier to WP_Object_Cache) so we can implement other ways to cache the compressed scripts/styles easily.

For example, we will could implement other caching methods like, separate SQLlite DB, Files...etc
You will understand it more when I will push the first commit.

**Comment by nash-ye** [comment]
The first stage completed, please tell me your opinion.

What I have done?
1 Re-build the plugin as instantiated classes:
`Dependency_Minification`
`DepMin_Admin`
`DepMin_Options`
`DepMin_SrcInfo`
`DepMin_Handler`
`DepMin_Collation`
`DepMin_Minify`
`DepMin_Minifier`
`DepMin_Minifier_Default`
`DepMin_Cache`
`DepMin_Cache_Default`
`DepMin_Cache_Interface`

2- Fix some performance bugs and re-write some codes to look better :)

**Comment by westonruter** [comment]
@nash-ye could you please close this and open PR another to the `develop` branch?

**Comment by westonruter** [comment]
Since it is opened to the `master` branch, the PR includes all pending commits from `develop` not just the new ones you have done.

**Comment by westonruter** [comment]
@nash-ye Also, you can see that the Travis build failed due to warnings and errors reported by PHP_CodeSniffer. See https://travis-ci.org/x-team/wp-dependency-minification/jobs/13916005#L133

**Comment by nash-ye** [comment]
@westonruter Ok :+1:

**Pull request closed without merging**
