### PR TITLE
Issue 41 Update i18n for WP 3.7 language packs

### PR DESCRIPTION
**Pull request by johnregan3**
Fix for Issue https://github.com/x-team/wp-dependency-minification/issues/41

### CODE REVIEW

**Comment by kucrut** [comment]
@johnregan3 You can use `hub pull-request -i 41 -b master -h x-team:issue-41` so #41 will be converted intto a PR.

**Comment by johnregan3** [comment]
@kucrut Thanks for this!  Weston's told me to do it before, but I could never decypher the exact syntax.  This helps a lot!

**Comment by kucrut** [comment]
:+1:

**Comment by westonruter** [comment]
@johnregan3 the text domain needs to be `dependency-minification` not `wp-dependency-minification`, as the the `wp-` prefix is just part of the GitHub repo name.

**Comment by johnregan3** [comment]
@westonruter I'll make that change.

**Pull request merged**
